# Generated by Django 3.0.5 on 2020-04-20 17:19

import datetime
from django.db import migrations, models
import olga.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=250, unique=True)),
                ('name', models.CharField(blank=True, max_length=250, null=True)),
                ('full_name', models.CharField(blank=True, max_length=250, null=True)),
                ('staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('admin', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('object', olga.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullName', models.CharField(default='Noname', max_length=100)),
                ('birthDate', models.DateField(null=True)),
                ('telephoneNumber', models.CharField(max_length=25, null=True)),
                ('workExperience', models.IntegerField(default=0)),
                ('position', models.CharField(max_length=100)),
                ('employmentDate', models.DateField(default=datetime.date(2020, 4, 20))),
            ],
        ),
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255)),
                ('purchaseDate', models.DateField(null=True)),
                ('employees', models.IntegerField()),
                ('schedule', models.CharField(max_length=255, null=True)),
                ('area', models.FloatField(null=True)),
                ('jobsNumber', models.IntegerField(null=True)),
                ('priceRent', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('customer', models.CharField(max_length=300, null=True)),
                ('alternativeLevel', models.CharField(max_length=300, null=True)),
                ('scope', models.CharField(max_length=1000, null=True)),
                ('budget', models.FloatField(null=True)),
                ('duration', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sprint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('taskSprint', models.CharField(max_length=255)),
                ('startDateSprint', models.DateField(default=datetime.date(2020, 4, 20))),
                ('responsible', models.CharField(max_length=255)),
                ('score', models.FloatField(default=0)),
                ('nameTask', models.CharField(max_length=200)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='Low', max_length=255)),
                ('startDate', models.DateField(default=None, null=True)),
                ('hoursNumber', models.FloatField(null=True)),
                ('completionStatus', models.CharField(choices=[('created', 'Created'), ('Selected for development', 'selected for development'), ('In process', 'in process'), ('Testing', 'testing'), ('Completed', 'completed')], default='Created', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('teamLead', models.CharField(max_length=255)),
                ('projectManager', models.CharField(max_length=255)),
                ('costPerHour', models.FloatField(null=True)),
                ('programers', models.CharField(max_length=255)),
                ('technologyStack', models.CharField(max_length=255)),
                ('participantsNumber', models.IntegerField(default=0)),
                ('fullName', models.CharField(max_length=100)),
                ('salary', models.FloatField(null=True)),
                ('employmentStatus', models.CharField(max_length=255)),
                ('direction', models.CharField(max_length=255)),
                ('position', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('capitalization', models.FloatField(null=True)),
                ('focus', models.CharField(max_length=200)),
                ('foundationDate', models.DateField(default=datetime.date(2020, 4, 20), null=True)),
                ('rating', models.FloatField(null=True)),
                ('manager', models.ManyToManyField(to='olga.Employee')),
            ],
        ),
    ]
