# Generated by Django 3.0.5 on 2020-04-20 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olga', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sprint',
            name='score',
            field=models.CharField(choices=[('виконано успішно', 'Виконано успішно'), ('Selected for development', 'selected for development'), ('In process', 'in process'), ('Testing', 'testing'), ('Completed', 'completed')], default='виконано успішно', max_length=255),
        ),
    ]
