# Generated by Django 3.0.5 on 2020-04-20 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olga', '0002_auto_20200420_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sprint',
            name='completionStatus',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='sprint',
            name='score',
            field=models.CharField(max_length=255),
        ),
    ]
