# Generated by Django 3.0.5 on 2020-04-20 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olga', '0003_auto_20200420_2012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sprint',
            name='priority',
            field=models.CharField(max_length=255),
        ),
    ]
